DROP TABLE IF EXISTS stations;

CREATE TABLE stations(
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(50) NOT NULL,
	company VARCHAR(15) NOT NULL, 
	prefecture VARCHAR(4) NOT NULL, 
	address VARCHAR(50) NOT NULL, 
	latitude DOUBLE NOT NULL, 
	longitude DOUBLE NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS matsuya_menus;

CREATE TABLE matsuya_menus(
	id INT NOT NULL AUTO_INCREMENT,
	category VARCHAR(5) NOT NULL, 
	name VARCHAR(30) NOT NULL,
	price INT NOT NULL, 
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS hanamaru_menus;

CREATE TABLE hanamaru_menus(
	id INT NOT NULL AUTO_INCREMENT,
	category VARCHAR(5) NOT NULL, 
	name VARCHAR(30) NOT NULL,
	price INT NOT NULL, 
	PRIMARY KEY (id)
);